# Generated by Django 2.2.6 on 2019-10-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_quartos', models.PositiveIntegerField()),
                ('n_suites', models.PositiveIntegerField()),
                ('n_sala_estar', models.PositiveIntegerField()),
                ('n_sala_jantar', models.PositiveIntegerField()),
                ('n_vaga_garagem', models.PositiveIntegerField()),
                ('andar', models.PositiveIntegerField()),
                ('valor_condominio', models.FloatField()),
                ('area', models.FloatField()),
                ('possui_armario', models.BooleanField()),
                ('descricao', models.CharField(max_length=200)),
                ('portaria_integral', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_quartos', models.PositiveIntegerField()),
                ('n_suites', models.PositiveIntegerField()),
                ('n_sala_estar', models.PositiveIntegerField()),
                ('n_vaga_garagem', models.PositiveIntegerField()),
                ('area', models.FloatField()),
                ('possui_armario', models.BooleanField()),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
    ]
