# Generated by Django 2.2.6 on 2019-10-30 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('cep', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=200)),
                ('rua', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='apartamento',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Imoveis.Endereco'),
        ),
        migrations.AddField(
            model_name='casa',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Imoveis.Endereco'),
        ),
    ]
