# Generated by Django 2.2.6 on 2019-10-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imoveis', '0002_auto_20191030_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='numero',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
